import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "surface-variant": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#404947",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        outline: "#707977",
        "outline-variant": "#bfc8c6",
        "surface-tint": "#306762",
        primary: "#003430",
        "on-primary": "#ffffff",
        "primary-container": "#0f4c47",
        "on-primary-container": "#84bbb4",
        "inverse-primary": "#99d1ca",
        secondary: "#006d40",
        "on-secondary": "#ffffff",
        "secondary-container": "#8ef5b5",
        "on-secondary-container": "#007243",
        tertiary: "#432800",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#613c00",
        "on-tertiary-container": "#f59e0c",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#b5ede6",
        "primary-fixed-dim": "#99d1ca",
        "on-primary-fixed": "#00201d",
        "on-primary-fixed-variant": "#144f4a",
        "secondary-fixed": "#91f8b8",
        "secondary-fixed-dim": "#74db9d",
        "on-secondary-fixed": "#002110",
        "on-secondary-fixed-variant": "#00522f",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        background: "#faf8ff",
        "on-background": "#131b2e",
      },
      fontFamily: {
        sans: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "system-ui", "sans-serif"],
        headline: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        metric: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", fontWeight: "700" }],
        "headline-xl-mobile": ["36px", { lineHeight: "44px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "metric-display": ["56px", { lineHeight: "60px", fontWeight: "700" }],
        "metric-display-mobile": ["42px", { lineHeight: "46px", fontWeight: "700" }],
        "body-lg": ["17px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "700" }],
      },
      spacing: {
        gutter: "1.25rem",
        "gutter-desktop": "2rem",
        margin: "1rem",
        "margin-tablet": "2rem",
        "margin-desktop": "3rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
